function importfile
%IMPORTFILE
%  Imports data from the system clipboard

%  Auto-generated by MATLAB on 09-Nov-2011 18:49:08

DELIMITER = ' ';
HEADERLINES = 2;

% Import the file
newData1 = importdata('-pastespecial', DELIMITER, HEADERLINES);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end

