function importfile1
%IMPORTFILE1
%  Imports data from the system clipboard

%  Auto-generated by MATLAB on 03-Dec-2011 10:11:16

DELIMITER = ' ';
HEADERLINES = 2;

% Import the file
newData1 = importdata('-pastespecial', DELIMITER, HEADERLINES);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end

