# Project: Project4
# Makefile created by Dev-C++ 4.9.8.0

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o VN_lib.o VN_math.o VN_user.o VN100.o $(RES)
LINKOBJ  = main.o VN_lib.o VN_math.o VN_user.o VN100.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" 
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/include/c++"  -I"C:/Dev-Cpp/include/c++/mingw32"  -I"C:/Dev-Cpp/include/c++/backward"  -I"C:/Dev-Cpp/include" 
BIN  = Project4.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS = $(INCS) 

.PHONY: all all-before all-after clean clean-custom

all: all-before Project4.exe all-after


clean: clean-custom
	rm -f $(OBJ) $(BIN)

$(BIN): $(LINKOBJ)
	$(CC) $(LINKOBJ) -o "Project4.exe" $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

VN_lib.o: VN_lib.c
	$(CC) -c VN_lib.c -o VN_lib.o $(CFLAGS)

VN_math.o: VN_math.c
	$(CC) -c VN_math.c -o VN_math.o $(CFLAGS)

VN_user.o: VN_user.c
	$(CC) -c VN_user.c -o VN_user.o $(CFLAGS)

VN100.o: VN100.c
	$(CC) -c VN100.c -o VN100.o $(CFLAGS)
