# Project: Project1
# Makefile created by Dev-C++ 4.9.8.0

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = "../../../../../../Firmware Library/FWLib/test1/examples/VN100/SPI/project/main.o" $(RES)
LINKOBJ  = "../../../../../../Firmware Library/FWLib/test1/examples/VN100/SPI/project/main.o" $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" 
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/include/c++"  -I"C:/Dev-Cpp/include/c++/mingw32"  -I"C:/Dev-Cpp/include/c++/backward"  -I"C:/Dev-Cpp/include" 
BIN  = test.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS = $(INCS) 

.PHONY: all all-before all-after clean clean-custom

all: all-before test.exe all-after


clean: clean-custom
	rm -f $(OBJ) $(BIN)

$(BIN): $(LINKOBJ)
	$(CC) $(LINKOBJ) -o "test.exe" $(LIBS)

"../../../../../../Firmware Library/FWLib/test1/examples/VN100/SPI/project/main.o": ../../../../../../Firmware\ Library/FWLib/test1/examples/VN100/SPI/project/main.c
	$(CC) -c "../../../../../../Firmware Library/FWLib/test1/examples/VN100/SPI/project/main.c" -o "../../../../../../Firmware Library/FWLib/test1/examples/VN100/SPI/project/main.o" $(CFLAGS)
