# Project: Project2
# Makefile created by Dev-C++ 4.9.8.0

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = examples/VN100/SPI/project/test2/main.o $(RES)
LINKOBJ  = examples/VN100/SPI/project/test2/main.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" 
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/include/c++"  -I"C:/Dev-Cpp/include/c++/mingw32"  -I"C:/Dev-Cpp/include/c++/backward"  -I"C:/Dev-Cpp/include" 
BIN  = Project2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS = $(INCS) 

.PHONY: all all-before all-after clean clean-custom

all: all-before Project2.exe all-after


clean: clean-custom
	rm -f $(OBJ) $(BIN)

$(BIN): $(LINKOBJ)
	$(CC) $(LINKOBJ) -o "Project2.exe" $(LIBS)

examples/VN100/SPI/project/test2/main.o: examples/VN100/SPI/project/test2/main.c
	$(CC) -c examples/VN100/SPI/project/test2/main.c -o examples/VN100/SPI/project/test2/main.o $(CFLAGS)
